### ISSUE TITLE
Generating valid HTML documents

### ISSUE THREAD

**Issue by parasyte** [yoshuawuyts/html#18]
Hi! This crate was brought to my attention, no doubt as a result of yesterday's release announcement. :)

I wanted to use this to generate a simple but valid HTML document and ran into some troubles immediately. I think there are some older issues (now closed) that are relevant, so I'll link them here:

- #1: Most of the issues I had was an inability to add children to "container" elements.
- #3: This looks like an aspirational API design, which would be far better than what I came up with.
- #12: This would be very much appreciated!

I started with a TDD-style test to generate a full HTML document:

```rust
#[test]
fn test_gen_html() {
    let output = gen_html();
    let expected = "<!DOCTYPE html>\
        <html lang=\"en\">\
            <head>\
                <meta charset=\"utf-8\">\
                <title>My site</title>\
            </head>\
            <body>\
                Hello, world!\
            </body>\
        </html>";

    assert_eq!(output, expected);
}
```

Then I implemented the `gen_html()` function, and ran into a number of issues. This was the best I could do, along with comments that rationalize the use of string interpolations:

```rust
use html::{metadata::Meta, root::Body};

pub fn gen_html() -> String {
    // We cannot add children to the `Head` element.
    // We can't even add text to the `Title` element.
    let head = format!(
        "<head>\
            {meta}\
            <title>My site</title>\
        </head>",
        meta = Meta::builder().charset("utf-8").build()
    );
    let body = Body::builder().text("Hello, world!").build();

    // There is no `DOCTYPE` element.
    // We cannot add children to the `Html` element.
    format!(r#"<!DOCTYPE html><html lang="en">{head}{body}</html>"#)
}
```

In short, elements like `metadata::Title` do not have an API for inserting a text child, `metadata::Head` and `root::Html` do not have an API for inserting any children (also, `Body` only allows text children), and there is no element representing `<!DOCTYPE html>` at all.

----

The questions I have are:

1. Is there an alternative API design to the one described in https://github.com/yoshuawuyts/html/issues/3#issuecomment-1501147977 that I haven't seen yet? Or does the API currently exist, and I just haven't been able to find it in the documentation?
2. I'm guessing the missing APIs are mostly a result of the spec generator not having knowledge of the full document structure. Is this accurate? If anyone were to contribute features to address the shortcomings, would they be adding to `html` or to `html-bindgen`? (Both, maybe, depending on context.)
3. What's the difference between `content::Body` and `root::Body` (if any)? Is the duplication an oversight? Which one is considered canonical?
4. There doesn't appear to be a use for the `TextElement` trait. Maybe `BodyChild`, `ParagraphChild`, et al. should have:
```rust
impl<T> From<T> for BodyChild where T: TextElement
```
5. Not a question, just an observation: `BodyChild` is lacking compared to `ParagraphChild`. The former only allows text elements, the latter allows text and several kinds of HTML elements. This follows from point 2, above.

**Comment by yoshuawuyts** [comment]
Hey there! :wave: - I really appreciate you filing this issue; it seems you've found a number of bugs! - I've filed individual issues for each bug, so they can be closed one-by-one via pull requests.

I should probably write a contribution document for this; but the way this project works is that we take the HTML spec, parse it into various intermediate JSON formats, and then use that to generate the `html-sys` and `html` crates from.

If child elements or attributes are missing, it usually points to a bug in the parsing step. That's no surprise, because we're almost exclusively dealing with one-off strings of prose. So the fix often involves writing a little parser for that string specifically. Once that's done you can re-run the `cargo xtask no-fetch` command (to do all parsing + codegen, but not re-fetch the spec) to update the generated code.

---

> Is there an alternative API design to the one described in https://github.com/yoshuawuyts/html/issues/3#issuecomment-1501147977 that I haven't seen yet? Or does the API currently exist, and I just haven't been able to find it in the documentation?

If we can fix the earlier bugs, the code to generate the HTML elements should be:

```rust
let tree = html::root::html::builder()
    .lang("en")
    .head(|head| {
        head.meta(|meta| meta.charset("utf-8"))
            .title(|title| title.text("My site"))
    })
    .body("Hello, world!")
    .build();
```

**Comment by parasyte** [comment]
The methods taking closures look amazing! And thank you for breaking this out into bite-sized tickets. That will make contributing much easier!
