### ISSUE TITLE
Formatting inside pre elements

### ISSUE THREAD

**Issue by jdonszelmann** [yoshuawuyts/html#40]
For a project, I was using axohtml, but I wanted to try out this crate because @yoshuawuyts has been tooting about it :)

Anyway, I ran into an issue. I'm trying to generate a lot of pre-rendered text. However, `to_string` seems to very neatly format the html generated. That's nice and all, but when preformatted text is reformatted, it loses all its preformatting! In my case, I end up with a ton of extra spaces and newlines which basically mean `html` is unusable for me. How we should solve this? I don't know. Probably don't do autoformatting inside \<pre\>s

**Comment by yoshuawuyts** [comment]
Hey there! Oh yeah, that doesn't sound great. Can you share a minimal repro so we can fix it?

As a hot fix we could probably revert the inline formatting.  But I'm thinking perhaps a better solution could be to disable indentation for all [text_content](https://docs.rs/html/latest/html/text_content/index.html) elements instead? Would that have fixed your issue?

**Comment by yoshuawuyts** [comment]
Or actually, now that I think about it — `<pre>` elements are probably the main element whose content we don't want to auto-indent I think?

**Comment by jonay2000** [comment]
Sure, I'll make an example (maybe even a PR if you'd like :). In any case, this is *hard* because you can always set the css `white-space: pre` and then have any element act like a pre. So ideally, we'd format nothing. But that's not nice either

**Comment by jonay2000** [comment]
Maybe a parameter on the builder allowing you to disable formatting on that element?

**Comment by jonay2000** [comment]
This is your minimal example:
```rust
use html::text_content::PreformattedText;

fn main() -> std::io::Result<()>{
    std::fs::write("test.html", PreformattedText::builder().text("test").build().to_string())
}
```
It outputs
```html
<pre>
    test
</pre>
```

While it should output 
```html
<pre>test</pre>
```

As a test case:

```rust
#[cfg(test)]
mod tests {
    use html::text_content::PreformattedText;

    #[test]
    fn test_pre() {
        assert_eq!(PreformattedText::builder().text("test").build().to_string(), "<pre>test</pre>".to_string())
    }
}

```

**Comment by jonay2000** [comment]
What would you say to 
```rust
PreformattedText::builder().text("test").autoformat(false).build().to_string()
```
(and maybe specifically for `pre` elements default autoformat to false)

**Comment by jonay2000** [comment]
The alternative is a `.render_not_formatted` or similar, but that wouldn't format the *entire* tree. Advantage is that we don't need to add a bool to every element.

**Comment by jdonszelmann** [comment]
thanks Yosh!
