### ISSUE TITLE
Can't Place Text Elements Inside Anchor

### ISSUE THREAD

**Issue by lsh** [yoshuawuyts/html#43]
Thanks for this crate!
It seems like [`AnchorChild`](https://docs.rs/html/latest/html/inline_text/children/enum.AnchorChild.html) doesn't have a `.text()` method for now. Ideally in the future we would be able to add elements like `<li>`, but for now `text` would allow users to workaround adding content.

**Comment by yoshuawuyts** [comment]
Thanks for raising this! It seems this is because of: https://github.com/yoshuawuyts/html/issues/9. The quickest fix for this is probably indeed to just white-list the `Anchor` element and add a `text` field to it. Similar to what we're planning to do for #41.
