### ISSUE TITLE
head element should support template and script children

### ISSUE THREAD

**Issue by atar13** [yoshuawuyts/html#50]
:wave: I noticed that the `head` element is only allowed to have the following elements as children (https://docs.rs/html/0.5.2/html/metadata/children/enum.HeadChild.html):
- base
- link
- meta
- noscript
- style
- title

However, the MDN docs say that these elements with the addition of  `template` and `script` can be used as children of `head` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head#see_also). 

Is this the intended behavior for this crate? If so, is there a workaround to be able to place `template` and `script` elements inside a `head`?

**Comment by parasyte** [comment]
FWIW, there is some info in this comment that describes what is happening: https://github.com/yoshuawuyts/html/issues/18#issuecomment-1506128143

IIUC, the parser needs to be adjusted to handle the various ways that MDN describes element nesting on different pages. MDN is used as the source of truth, but it's written in English prose and not a general grammar that is easy for software to parse. It's a bug.
