### ISSUE TITLE
Produced HTML has too many spaces

### ISSUE THREAD

**Issue by henkkuli** [yoshuawuyts/html#60]
First of all, I'd like to say that I really like the idea of having a typed html crate. It makes creating correctly nested html easy.

I also like the idea of creating properly indented html. Unfortunately this is not trivial, and in practice adding spaces can change the meaning of produced markup in significant ways. Consider
```rust
use html::text_content::Paragraph;
let p = Paragraph::builder()
    .span(|span| span.style("color: red").text("Hel"))
    .text("lo World!")
    .build();
println!("{p}");
```
This produces
```html
<p>
    <span style="color: red">
        Hel
    </span>
    lo World!
</p>
```
which is not what I would expect, and semantically this is also incorrect. In particular, this renders as `Hel lo World!` while I would expect there to be no space between `Hel` and `lo`.

Now the first idea to fix this could be to have a list of tags which can have indentation added without affecting the rendering result. Unfortunately this is doomed as almost any element can be made to be space-conscious by adding `white-space: pre` style.

I think the only option that can always guarantee correct semantics for the produced html is to never add extra spaces between tags, even if that means losing the nice indentation. I think the crate should strive for correctness of the produced output over the prettiness. The crate can also provide an alternative API, like `render_pretty` to produce prettified output, but it should be clearly documented that this can result in different semantics of the output.

Ps. It seems, that this issue has already been discussed before at least in #40, #42 and #58.

**Comment by yoshuawuyts** [comment]
Thanks for reporting this. I've filed https://github.com/yoshuawuyts/html/pull/61 which disables pretty-printing for our `Display` impl, which hopefully can fix the issue permanently.

**Comment by henkkuli** [comment]
Thanks for fixing this. I like the fix that `Debug` now pretty-prints the output while `Display` ensures correctness. This way you can still read nicely-formatted HTML while debugging while still getting property-formatted HTML as output.
